Update patch set 1
Patch Set 1: Code-Review-1

Well.. Reverted partially NavigationBarFragment changes from http://gerrit.aicp-rom.com/#/c/54688/10/packages/SystemUI/src/com/android/systemui/statusbar/phone/NavigationBarFragment.java

Also picked current change and linked fwb change... But no go: 
ERROR: /home/doc/aicpO8/frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/phone/NavigationBarFragment.java:252.9: The method notifyNavigationBarScreenOn() in the type NavigationBarFragment is not applicable for the arguments (boolean)
ERROR: /home/doc/aicpO8/frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/phone/NavigationBarFragment.java:846.13: The method notifyNavigationBarScreenOn() in the type NavigationBarFragment is not applicable for the arguments (boolean)

Patch-set: 1